# Generated by Django 3.1.2 on 2021-01-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Add picture'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
